title: "Musings of a Developer"
author: "Connor Moreside"
description: "Connor Moreside's Personal Blog"
more: "read more »"
url: "https://moreside.io"
baseurl: "/"
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - projects.md
  - about.md

comments:
  disqus: "disqus-contrast"

links:
  - github: "https://github.com/cmoresid"
  - linkedin: "https://www.linkedin.com/in/cmoreside/"
  - twitter: "https://twitter.com/c_moreside"
  - envelope: "mailto:connor@moreside.io"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
