title: "Musings of a Developer"
author: "Connor Moreside"
description: "Really cool blog about ... something"
more: "read more »"
url: "https://moreside.io"
baseurl: "/"
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md

comments:
  disqus: "disqus-contrast"

links:
  - github: "https://github.com/moresid"
  - envelope: "mailto:niklas.buschmann@posteo.de"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
